### ISSUE TITLE
Coloration error

### ISSUE THREAD

**Issue by golpilolz** [Keenegan/drupal-patch-color#16]
I've got an error on the page. Some undefined values

https://www.drupal.org/files/issues/2020-04-27/Add_pre_post_query_alter_hooks_.patch

**Comment by Keenegan** [comment]
`Index: src/Plugin/search_api/backend/SearchApiElasticsearchBackend.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================`

This patch must have been generated by a tool (IDEA ? Jetbrains ?) that is not supported yet by drupal patch color, I'll try to fix this soon

**Comment by Keenegan** [comment]
IMO the patch is not in the right format (it should contains a "diff --git (filename)"), I'm not sure if this is valid for drupal, but since this is the first time I see this, I'm going to assume that's not used by many users, and not support the format.

I just fixed the undefined errors, so the patch is still readable, the new version should be available soon.

Feel free to reopen this issue if you come across more of this format
